name: Sync SFTP to S3

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Enables manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/sftp_key
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/sftp_key
      - name: Sync Files from SFTP to Local
        run: |
          mkdir -p /tmp/sftp_files
          sftp -i ~/.ssh/sftp_key -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }} <<EOF
          lcd /tmp/sftp_files
          get -r -p .
          bye
          EOF
      - name: Sync Local Files to S3 (Add-Only)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: "sftp-destination-bucket-5ff2c06d"
        run: |
          aws s3 sync /tmp/sftp_files s3://${{ env.BUCKET_NAME }} --size-only --exact-timestamps --no-progress --region eu-west-3
